name: Update README with Changelog

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    # PERMISSÃO ADICIONADA AQUI!
    # Sem isso, a action não consegue fazer o commit de volta.
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get last commit message
        id: last_commit
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Update README with changelog
        run: |
          COMMIT_MESSAGE="${{ steps.last_commit.outputs.message }}"
          if ! grep -q "## Changelog" README.md; then
            echo -e "\n## Changelog\n" >> README.md
          fi
          sed -i "/## Changelog/a\- $(date '+%Y-%m-%d %H:%M') - $COMMIT_MESSAGE" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: update changelog with last commit message" || echo "No changes to commit"
          git push