name: Showcase de Ações Agendadas

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 23 * * 6'

jobs:
  nightly-file-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Contar todos os arquivos à meia-noite
        run: |
          COUNT=$(find . -type f | wc -l)
          echo "Contagem da meia-noite: Existem $COUNT arquivos no projeto."

  conditional-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Rodar apenas durante a noite (entre 00:00 e 08:00 UTC)
        if: github.event.schedule == '0 0 * * *'
        run: echo "Esta tarefa está rodando de madrugada, conforme agendado."
      - name: Rodar apenas aos Sábados
        if: github.event.schedule == '0 23 * * 6'
        run: echo "Esta tarefa está rodando no Sábado, conforme agendado."